In [2]:
import torch

t1 = torch.tensor([[1,2]])
t2 = torch.tensor([[3,4]])

t1*t2

tensor([[3, 8]])

In [3]:
t1.shape

torch.Size([1, 2])

In [4]:
x = torch.randn(10, 1)
print(x)

# 找到每一行中最大的两个元素
values, indices = torch.topk(x, 2, dim=0)

indices

tensor([[-0.2705],
        [ 0.3923],
        [ 0.7780],
        [ 0.2357],
        [-1.5806],
        [-1.2319],
        [-0.3480],
        [-0.7451],
        [-1.5221],
        [-1.8520]])


tensor([[2],
        [1]])

In [5]:
t3 = torch.zeros(100, 1)

In [ ]:
[1, 10, 6]/2